### ISSUE TITLE
[Request] VPM support

### ISSUE THREAD

**Issue by Andazeus** [Markcreator/Unity-Tools#2]
Hey there!

As you have probably heard, VRC will enforce use of the Creator Companion starting next year.

It comes with the ability to create project templates that can automatically pull packages and insert them into new projects as well as automatically update packages.

Custom repositories and packages are supported as well, but in order to take advantage of most of the advanced automation features, packages need to be provided in the VPM format. Tooling and documentation on creating a VPM package is provided here:
https://github.com/vrchat-community/template-package

Since I consider the Size Profiler and Texture Compressor to be fantastic quality of life additions for avatar creation and management, I would love for them to be available in a custom VPM repo to be able to keep them included in my projects and updated automatically.

Are there any plans on looking into that functionality?

**Comment by Markcreator** [comment]
Great suggestion! I will see about offering VPM packages for all the tools here now that the VCC will be the primary way to manage packages
